### ISSUE TITLE
Client Meeting Minutes

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#1]
This task includes the meeting minutes with the client

**Comment by khairusyaidy** [comment]
How many hours are required for each staff to meet within 1 week?
- Follow MOM law

**Comment by khairusyaidy** [comment]
Do you want the manager and assistant manager to have the same privileges in the system? 
- For now manager and assistant manager can have the same privileges.
- The IT admin can have a feature that will change privileges in the system for different roles in the future.

**Comment by MIFBS89** [comment]
For the top three staff with the lowest workload, how do you define workload?

- Number of hours worked
- Weekends
- After office hours
- 2 branches per staff to be considered
- Part timers can be considered (Manager, staff & pharmacy)

**Comment by khairusyaidy** [comment]
All necessary questions are answered.
