### ISSUE TITLE
1.2.2 Product Functionality

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#10]
1. Task title ID: #10
2. What is the task about? Please describe in detail.
The task is to define and document the major functions that the product must perform or allow users to perform. These functions are categorized into three user roles: Managers, Staff, and IT Administrators, with additional general functionalities.

3. What are the goals of the task? Please describe in detail.

- Clearly outline the key functionalities that the product must deliver for each user role (Managers, Staff, IT Administrators, and General).
- Ensure that the product meets the specified requirements and user needs.
- Provide a high-level overview of the product's functionality to guide development and testing efforts.

4. Success or completion criteria. Please describe in detail.

- A detailed list of the major functions is provided, covering the requirements for Managers, Staff, IT Administrators, and General users.
- Each function is described concisely and comprehensively, ensuring a shared understanding of what the product should do.
- The list includes any relevant details mentioned in Section 3 of the project description.   

5. Allocated time
5 days

6. Start date and end date of the issue/task
Start Date: 18th September 2023
End Date: 23rd September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Khairyl (khairusyaidy)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
In-Progress

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by mdmarhakim** [comment]
Describe the work done in detail.
A detailed list of the major functions (PF1 to PF11)  is provided, covering the requirements for Managers, Staff, IT Administrators, and General users.

Has this work been committed to the repo?
Yes.

How does the work affect 4. Success or completion criteria?
- A detailed list of the major functions (PF1 to PF11) is provided, covering the requirements for Managers, Staff, IT Administrators, and General users.
- Each function is described concisely and comprehensively, ensuring a shared understanding of what the product should do.
- The list includes any relevant details mentioned in Section 3 of the project description.   

Start date and end date of the work done
Start Date: 18th September 2023
End Date: 23rd September 2023
