### ISSUE TITLE
1.2.3 Assumptions and Dependencies

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#11]
1. Task title ID: #11
2. What is the task about? Please describe in detail.
The task involves identifying and documenting assumptions and dependencies for a project. Assumptions are factors or conditions that are believed to be true but not yet verified, and dependencies are external factors or components that the project relies on. This information is critical for project planning and risk management.

3. What are the goals of the task? Please describe in detail.

- To clearly identify and document all major assumptions related to the project.
- To identify and document all external dependencies that could impact the project's progress and success.

4. Success or completion criteria. Please describe in detail.

- All major assumptions that might significantly affect the project's design are documented.
- All external dependencies that the project relies on are identified and documented.
- The document is reviewed and approved by relevant stakeholders.

5. Allocated time
5 days

6. Start date and end date of the issue/task
Start Date: 18th September 2023
End Date: 23rd September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Khairyl (khairusyaidy)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
In-Progress

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by mdmarhakim** [comment]
Describe the work done in detail.

- To clearly identify and document all major assumptions related to the project.
- To identify and document all external dependencies that could impact the project's progress and success.

Has this work been committed to the repo?
Yes.

How does the work affect 4. Success or completion criteria?
The work of clearly identifying and documenting major assumptions and external dependencies significantly impacts the success or completion criteria of a project. By doing so, it enhances the project's ability to proactively manage risks, uncertainties, and external factors that could affect timelines, resources, quality, and stakeholder expectations. Success criteria are thus closely tied to the project's capacity to navigate and adapt to these critical elements, ensuring that it stays on track and achieves its objectives.

Start date and end date of the work done
Start Date: 18th September 2023
End Date: 23rd September 2023
