### ISSUE TITLE
1.3.4 Non-Functional Requirements

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#12]
1. Task title ID: #12

2. What is the task about? Please describe in detail.
The task is to address and implement the non-functional requirements (NFRs) listed for the system. These NFRs are crucial for ensuring the overall quality, security, scalability, and usability of the system. They encompass various aspects such as multilingual support, security measures, scalability, accessibility, availability, user interface design, logging, and backup/recovery.

3. What are the goals of the task? Please describe in detail.
The goal of the non-functional requirement task is to ensure a comprehensive, efficient, and user-friendly system. First and foremost, it must support multiple languages to cater to a global and diverse user base. As the user community grows, the system needs the capability to accommodate an increasing number of users and the associated data seamlessly. Data protection is vital, which is why a robust backup and recovery system needs to be established to guard against potential losses. Recognizing the shift towards mobile technology, the system must be versatile, ensuring accessibility and full functionality across a variety of devices, from desktops to mobile phones and tablets. Continuity of service is essential, which means aiming for consistently high availability and limiting downtime, whether due to maintenance or other challenges. User experience is paramount; hence the interface should be intuitive, fostering effortless navigation for users of all backgrounds and expertise levels. Lastly, to ensure transparency and maintain trust, every change made within the system should be meticulously logged, providing a clear trail for accountability purposes.

4. Success or completion criteria. Please describe in detail.

- Successful implementation of multilingual support with at least three languages supported.
- The system should handle a 50% increase in users and data load without performance degradation.
- All data should be encrypted using industry-standard encryption methods, and secure login methods like two-factor authentication should be in place.
- The system should be accessible and fully functional on common mobile devices and tablets, with responsive design.
- Achieve at least 99% uptime over a three-month period.
- Users should find the interface easy to use, with positive feedback in user testing.
- All changes made within the system should be accurately logged, and logs should be accessible to administrators.
- Implement regular automated backups with a recovery plan tested successfully.

5. Allocated time
5 days

6. Start date and end date of the issue/task
Start Date: 15th September 2023
End Date: 19th September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Marhakim (mdmarhakim)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
In-Progress

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by MIFBS89** [comment]
I changed the PR (Performance requirement) and etc to NFR. All considered as NFR. Only thing needed to do is to ensure that numbering is correct

Removed duplicate entries from the requirement

**Comment by mdmarhakim** [comment]
NA

**Comment by mdmarhakim** [comment]
Describe the work done in detail.
List out the following non-functional requirement which are as follows,

- NFR1: The system should support multiple languages.
- NFR2: The system should be able to handle an increasing number of users and data.
- NFR3: There should be a robust backup and recovery system in place.
- NFR4: The system should be accessible and fully functional on various devices, including mobile phones and tablets.
- NFR5: The system should aim for high availability, with minimal downtime for maintenance or other issues.
- NFR6: The interface should be intuitive and easy to navigate for all types of users.
- NFR7: All changes made in the system should be logged for accountability.

Has this work been committed to the repo?
Yes.

How does the work affect 4. Success or completion criteria?
The success or completion criteria for the work are rooted in its ability to be user-centric, scalable, robust, transparent, and versatile across various platforms and devices.

Start date and end date of the work done
Start Date: 15th September 2023
End Date: 19th September 2023
