### ISSUE TITLE
1.5 (Annex) Use Case Descriptions

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#13]
1. Task title ID: #13
2. What is the task about? The task is to describe each use cases provided in the diagram.
3. What are the goals of the task? To have a clear and concise understanding of the purpose of each use case
4. Success or completion criteria. Each use case is describe properly including alternative scenarios.
5. Allocated time - 4 days
6. Start date and end date of the issue/task - 19 sep - 23 sep 2023
7. Who is the owner?Izhar
8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
9. What is the Priority of the task? HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by MIFBS89** [comment]
Updated use case based on the latest use case diagram

**Comment by WanTengTiew** [comment]
15 Use Case Description completed

**Comment by MIFBS89** [comment]
Completed all description
