### ISSUE TITLE
1.3.4.2 Safety and Security Requirements

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#14]
1. Task title ID: #14
2. What is the task about? Please describe in detail.
Specify those requirements that are concerned with possible loss, damage, or harm that could result from the use of the product. Define any safeguards or actions that must be taken, as well as actions that must be prevented. 
4. What are the goals of the task? Please describe in detail.
The goals of the task are to identify, document, and implement safety and security requirements that are relevant to pharmacy web assignments. These goals might include ensuring patient data confidentiality, preventing unauthorized access, and complying with relevant healthcare regulations.
6. Success or completion criteria. Please describe in detail.
Implementation of security measures, such as encryption and authentication.
Compliance with relevant industry standards or regulations.
Successful testing and verification of security controls
8. Allocated time
4 days
10. Start date and end date of the issue/task
20-sep to 23-sep
12. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Khai
13. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
To do
14. What is the Priority of the task? HIGH / MEDIUM / LOW
High

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
laid out the requirements in the report
3. Has this work been committed to the repo? yea
4. How does the work affect 4. Success or completion criteria? 
6. Start date and end date of the work done
20sep - 23sep

**Comment by khairusyaidy** [comment]
written and edit the requirements in the report
