### ISSUE TITLE
1.3.4.1 Performance Requirements

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#16]
1. Task title ID: #16
2. What is the task about? This is to describe all the non-functional requirement and all other requirements related to performance
3. What are the goals of the task? To ensure that all requirements are in writing to prevent confusion
4. Success or completion criteria. No confusion or fuss about the requirements
5. Allocated time 9 days
6. Start date and end date of the issue/task 15-23 sept
7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
9. What is the Priority of the task? HIGH / MEDIUM / LOW

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by MIFBS89** [comment]
All performance requirement have been amended accordingly.

**Comment by MIFBS89** [comment]
Closed as completed
