### ISSUE TITLE
1.3.3 Use-Case Model

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#18]
1. Task title ID: #18

2. What is the task about? Please describe in detail.
The task is to develop and implement specific functionalities within the pharmacy scheduling management system to cater to the needs of the Manager role. This includes creating use cases for viewing different types of staff (branch staff/pharmacist), viewing staff assignments, and allocating jobs while considering branch assignments. These functionalities are crucial for efficient staff management and job allocation in the pharmacy.

3. What are the goals of the task? Please describe in detail.

- To enhance the pharmacy scheduling management system by adding features that enable Managers to effectively manage staff and job allocation.
- To provide Managers with the ability to differentiate between branch staff and pharmacists, facilitating better decision-making regarding task allocation.
- To enable Managers to view the current assignments of staff, ensuring proper workload distribution.
- To implement job allocation functionality that takes into account staff preferences, availability, and branch assignment, ensuring optimal task distribution.

4. Success or completion criteria. Please describe in detail.
The task will be considered successfully completed when the following criteria are met:

- The system allows Managers to view and distinguish between different types of staff (branch staff/pharmacist).
- Managers can access a clear and updated view of staff assignments.
- Job allocation functionality is implemented, allowing Managers to allocate tasks based on staff preference, availability, and branch assignment.
- The allocated time, start date, and end date of the issue/task are met as specified.
- The task is fully tested and integrated into the pharmacy scheduling management system without critical issues or bugs.
- The system owner or stakeholders have approved and verified the functionality.

5. Allocated time
5 days

6. Start date and end date of the issue/task
Start Date: 15th September 2023
End Date: 23th September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Izhar

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
In-Progress

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by MIFBS89** [comment]
Completed. Latest use case is in the report
