### ISSUE TITLE
1.3.6 Activity Diagram

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#19]
1. Task title ID: #19
2. What is the task about? Please describe in detail.
The task involves creating an Activity Diagram, which is a type of visual representation used in software engineering and business process modeling to illustrate the flow of activities or processes within a system or organization. In this case, the task should specify what system or process the Activity Diagram will represent and any specific details about its scope.
4. What are the goals of the task? Please describe in detail.
The goals of creating an Activity Diagram could include:
To provide a clear, visual representation of a specific process or system.
To document the sequence of activities, decision points, and interactions within that process.
To aid in understanding and analyzing the workflow for process improvement or system design.
5. Success or completion criteria. Please describe in detail.
The creation of a well-documented Activity Diagram that accurately represents the chosen process or system.
6. Allocated time
6 days
7. Start date and end date of the issue/task
20-sep - 23-sep
8. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Khai
9. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
Completed
10. What is the Priority of the task? HIGH / MEDIUM / LOW
High

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by MIFBS89** [comment]
1. Task title ID: #19
2. The task is to include the activity diagram to the report. The activity includes from assigning workload to staff, viewing workload, and staff's ability to view/accept/add/edit availability.
3. The goal is to ensure that we understand the workflow of the system and how the activity runs from start to finish.
4. It is a success for the first draft as we are able to understand the workflow. Work must be done to ensure that activities by the system are understood in better terms
5. 6 days 
6. Start date: 19 September 2023 - 24 September 2023
7. izhar (mifbs89).
8. In-Progress
9. What is the Priority of the task? HIGH

**Comment by MIFBS89** [comment]
Activity diagram created as a draft. For team to review if it is necessary to edit.

**Comment by khairusyaidy** [comment]
Amended the activity diagram in a new tab. 
https://app.diagrams.net/#G1I0oh8nMMpVpEwYQGH89ga4AxOt6UxHXS#%7B%22pageId%22%3A%22x7hcWKxb8Rh_IPolR_eg%22%7D

**Comment by MIFBS89** [comment]
Seems better than the draft

**Comment by khairusyaidy** [comment]
Marking as completed
