### ISSUE TITLE
1.3.1 User Interface Requirements

### ISSUE THREAD

**Issue by MIFBS89** [khairusyaidy/P7-1#20]
1. Task title ID: #20

2. What is the task about? Please describe in detail.
Develop the User Interface for the Pharmacy Workload Management System.

3. What are the goals of the task? Please describe in detail.

- Create a user-friendly interface for pharmacy staff and management to interact with the workload management system.
- Provide easy access to personnel information, workload schedules, and availability status.
- Ensure that the interface is informative, allowing users to gain insights into employee involvement and availability at any given time.

4. Success or completion criteria. Please describe in detail.

- User interface design and layout finalized and approved by the project stakeholders.
- The interface allows users to view and update personnel information.
- Users can access and modify workload schedules for pharmacy staff.
- Availability status of employees can be easily monitored through the interface.
- The interface is responsive and functional across common web browsers.

5. Allocated time
5 days

6. Start date and end date of the issue/task
Start Date: 18th September 2023
End Date: 22nd September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Marhakim (mdmarhakim)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
Completed

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by mdmarhakim** [comment]
NA

**Comment by mdmarhakim** [comment]
List out the following user interface requirements in the M1 report which are as follows:

General Requirements
Manager's Interface
Employee's Interface
IT Administrator's Interface
Also, the below following has been followed through as per above description.

Describe the work done in detail.
Has this work been committed to the repo?
How does the work affect 4. Success or completion criteria?
Start date and end date of the work done
