### ISSUE TITLE
1.3.5 Other Requirements

### ISSUE THREAD

**Issue by mdmarhakim** [khairusyaidy/P7-1#21]
1. Task title ID: #21
2. What is the task about? This task is to include all NFR that are not part of the scope given in the context
3. What are the goals of the task? To indicate the remaining NFRs that are not part of the scope
4. Success or completion criteria. Completion would be having some NFRs added to it.
5. Allocated time - 4 days 
6. Start date and end date of the issue/task - 19 Sep 2023 - 23 sep 2023
7. Who is the owner? Izhar
8. The status of the task. This is usually "To-Do" initially **To-Do** / In-Progress / Completed
9. What is the Priority of the task? MEDIUM

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by MIFBS89** [comment]
Added a few NFRs to this section

**Comment by MIFBS89** [comment]
Mark as completed. No new NFRs to add
