### ISSUE TITLE
1.6 (Annex) Data Dictionary

### ISSUE THREAD

**Issue by mdmarhakim** [khairusyaidy/P7-1#23]
1. Task title ID: #23
2. What is the task about? This task is to include all the definitions of the phrases that were used by the team
3. What are the goals of the task? Ensure that people not from this project understands the report better.
4. Success or completion criteria. No phrase or words that cannot be understood by someone not in the project
5. Allocated time - 4 days
6. Start date and end date of the issue/task 19-23 september
7. Who is the owner? Khai and partly Izhar
8. The status of the task. This is usually "To-Do" initially To-Do / **In-Progress** / Completed
9. What is the Priority of the task? **HIGH** / MEDIUM / LOW

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
Include the data dictionary in the report
3. Has this work been committed to the repo? yea
4. How does the work affect 4. Success or completion criteria? All phrases to be understood by anyone has been specified in the report
5. Start date and end date of the work done 19-23 sep

**Comment by khairusyaidy** [comment]
Amended and add one point to the exisiting Data Dictionary
