### ISSUE TITLE
2.3.1 User Interface Requirements Changes

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#26]
Task title ID: User Interface Requirements Changes

What is the task about? Please describe in detail.
Develop the User Interface for the Pharmacy Workload Management System.

What are the goals of the task? Please describe in detail.

Allocated time
1 day

Start date and end date of the issue/task
Start Date: 28th October 2023
End Date: 28th October 2023

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Marhakim (mdmarhakim)

The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
Completed

What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
Updated the below following as per feedbacks provided from M1 report.

- General Interface
- Manager Interface
- Staff Interface
- IT administrator Interface
