### ISSUE TITLE
2.4.1 Component Diagram

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#29]
Task title ID: 2.4.1 Component Diagram

What is the task about? Please describe in detail.
The task is to address and implement the non-functional requirements (NFRs) listed for the system. These NFRs are crucial for ensuring the overall quality, security, scalability, and usability of the system. They encompass various aspects such as multilingual support, security measures, scalability, accessibility, availability, user interface design, logging, and backup/recovery.

What are the goals of the task? Please describe in detail.
This diagram presents a component diagram based on the Model-View-Controller (MVC) 
architecture. It comprises three primary elements: Models, Views, and Controllers. The Models 
include entities such as Staff, Managers, Job, IT Administrator, and Database. The Views section 
encompasses interfaces like Login, Profile Management, Add Availability, Job Allocation, View 
Job, and Account Management. Lastly, the Controllers are responsible for various functionalities, 
including Login, Profile Management, Manage Availability, Allocate Jobs, View Jobs, Account 
Management, and 2 Factor Authentication. This structure effectively delineates the system's 
organization and operational flow.

Success or completion criteria. Please describe in detail.

Each user interface component is connected to a relevant controller, ensuring a distinct separation 
between the interface and the core business processes. The controllers interact with designated 
models for handling tasks ranging from user login to job assignments and managing staff details. 
This structure demonstrates an organized approach to software design, emphasizing clear roles and 
interactions for efficient system operation.

Allocated time
1 day

Start date and end date of the issue/task
Start Date: 28th October 2023
End Date: 28th October 2023

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Benjamin

The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
Completed

What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by BenjaminChiam** [comment]
Having meticulously analyzed the requirements and architecture of the Employee Management System, we have successfully designed a comprehensive Component Diagram. This diagram vividly illustrates the essential software components and their interrelationships, ensuring a clear understanding of the system’s structure and functionality. Key components such as the User Interface, Authentication System, Database Management, and others have been detailed, showcasing how each interacts within the system architecture.

Moving forward, this diagram will serve as a crucial reference, guiding our development team throughout the implementation process, ensuring alignment with the system’s design and functional specifications. We believe that this well-structured Component Diagram lays a solid foundation for the effective and efficient development of our Employee Management System, driving us towards a successful project completion.
