### ISSUE TITLE
Gantt Chart Changes

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#33]
Update gantt chart for M2 and M3 as per commented

**Comment by BenjaminChiam** [comment]
After a thorough review and update of the project's timelines and tasks, the Gantt chart for Milestone 2 and Milestone 3 of our Employee Management System development project has been successfully updated. The revisions made are a reflection of our strategic planning, accommodating any new insights, adjustments, and realignments necessary to maintain project efficacy and timeliness.

Milestone 2, focusing on Design Specifications and Management, has been meticulously updated to reflect the precise tasks, dependencies, and durations, ensuring a smooth transition into the execution phase. Similarly, Milestone 3, emphasizing Test Plan & Prototype, has been refined to accurately portray our testing strategies, prototyping, and feedback iterations, ensuring a comprehensive approach towards quality assurance.

With this updated Gantt chart, we are equipped with a clear, visual roadmap that will guide our team through each phase, fostering collaboration, tracking progress, and ensuring that every aspect of the project aligns with our schedule and objectives. This marks the completion of the updating task, and we are ready to forge ahead with enhanced clarity and a well-defined direction.
