### ISSUE TITLE
Creation of gantt chart

### ISSUE THREAD

**Issue by MIFBS89** [khairusyaidy/P7-1#4]
Creation of gantt chart for the whole of project,

Including:
M1
M2
M3

**Comment by MIFBS89** [comment]
Due 18 september 2023

**Comment by khairusyaidy** [comment]
[2101 Gantt chart P7-1.xlsx](https://github.com/khairusyaidy/P7-1/files/12598445/2101.Gantt.chart.P7-1.xlsx)

Created Gantt chart for M1 M2 M3. Please refer to the assignment of roles/tasks.

**Comment by MIFBS89** [comment]
Keep it open until everyone review it

**Comment by mdmarhakim** [comment]
I have uploaded the gantt chart to OneDrive, for easier edit. Kindly use your school email to access and edit the gantt chart excel.

**Comment by khairusyaidy** [comment]
Thanks marhakim. Gantt chart can be accessed through
https://sitsingaporetechedu-my.sharepoint.com/:x:/r/personal/2102932_sit_singaporetech_edu_sg/_layouts/15/Doc.aspx?sourcedoc=%7B22935A6E-0C29-4A96-A467-8F9C7A0BEDBF%7D&file=2101.Gantt.chart.P7-1.xlsx&action=default&mobileredirect=true
