### ISSUE TITLE
1.1.1 Product Scope

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#5]
1. Task title ID: #5
2. What is the task about? Please describe in detail.
The task involves the development and implementation of a web-based Workload Management System for a pharmacy shop. This system will centralize the allocation and management of work tasks across multiple branches of the pharmacy. It will include features such as real-time scheduling, job assignments, staff availability tracking, and employee preferences for up to five weeks in advance. The task encompasses the design, development, testing, and deployment of the system.

3. What are the goals of the task? Please describe in detail.

- Enhance Operational Efficiency: The primary goal is to improve operational efficiency by providing real-time insights into manpower availability and workload distribution, enabling better resource planning.
- Improve Service Quality: The task aims to enhance service quality across all pharmacy branches by ensuring the right staff is allocated to meet customer demands effectively.
- Balance Organizational Needs and Employee Well-being: The task seeks to strike a balance between organizational requirements and employee well-being by enabling advanced scheduling that supports work-life balance.
- Automate Workload Management: By automating manual processes, the task aims to reduce errors and free up managerial time, contributing to a more organized and productive work environment.
- Align with Company Goals: The task aligns with the broader company goals of improving work-life balance, increasing productivity, and maintaining a high standard of service quality.

4. Success or completion criteria. Please describe in detail.

- Successful deployment of the web-based Workload Management System.
- Real-time visualization of staff workload for managers.
- Capability for staff to indicate availability and job preferences up to five weeks in advance.
- Reduced manual workload management processes.
- Improved resource allocation and service quality.
- Enhanced work-life balance for employees.
- Positive feedback from administrative staff and employees regarding system usability and effectiveness.

5. Allocated time
22 days

6. Start date and end date of the issue/task
Start Date: 28th August 2023
End Date: 23th September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Marhakim (mdmarhakim)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
Completed

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by mdmarhakim** [comment]
The benefits has been briefly described with the product in the M1 report as per mentioned in the above details.

**Comment by khairusyaidy** [comment]
Marking as completed. Thanks!
