### ISSUE TITLE
1.1.2 Related Background Literature

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#6]
1. Task title ID: #6
2. What is the task about? Please describe in detail.
Create a new enterprise management software system that incorporates elements from the research papers mentioned and takes inspiration from the Workday application.

3. What are the goals of the task? Please describe in detail.

- System Development: Develop a new software system for enterprise management, leveraging the research on LDAP, project management, workload importance, and best practices from Workday.

- Data Consistency: Ensure data consistency and accuracy by centralizing information in LDAP databases while allowing for easy updates through user-friendly interfaces.

- Resource Allocation: Implement a resource allocation module inspired by the project management system in the research papers to optimize resource utilization.

- Workload Importance: Integrate the concept of workload importance from the "Managing Workload Importance in Enterprise DBMSs" paper to improve resource allocation strategies.

- User Experience: Create a unified, personalized, and real-time user experience similar to Workday for managing HR, financials, and other enterprise functions.

4. Success or completion criteria. Please describe in detail.

- Successful development and deployment of the enterprise management software.
- User-friendly interfaces for data updates and resource allocation.
- Improved data consistency and accuracy.
- Optimized resource allocation based on workload importance.
- Positive user feedback and acceptance within the organization.

5. Allocated time
22 days

6. Start date and end date of the issue/task
Start Date: 28th August 2023
End Date: 23th September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Khairyl (khairusyaidy)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
In-Progress

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by BenjaminChiam** [comment]
Describe the work done in detail:
Before conducting the development process, our team conducted some research on background literature and related development materials. We believe that the information we gather will provide our team with operational knowledge and technical expertise on creating a type of software for enterprise management systems.

3 research papers and 2 applications currently on the market was studied for information on software development process.

- An Automated Enterprise IT Management System Based on LDAP (Research paper)
- A project management system for time planning and resources allocation (Research paper)
- Managing Workload Importance in Enterprise DBMSs (Research paper)
- Workday Enterprise Management Cloud (Competing software)
- Oracle PeopleSoft Applications (Competing software)

Has this work been committed to the repo?
Yes.

How does the work affect 4. Success or completion criteria?

- Relevant background research was done to help the team gain a better understanding of Enterprise software development.

- Various notes and important information from the research and competing software was reviewed by the team.

- The research materials have helped our team plan the timeline and features for the project.


Start date and end date of the work done
Start Date: 18th September 2023
End Date: 23rd September 2023

**Comment by BenjaminChiam** [comment]
Section completed, marked as closed.
