### ISSUE TITLE
1.1.3 Intended Audience and Document Overview

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#7]
1. Task title ID: #7
2. What is the task about? Please describe in detail.
The task at hand is to create a comprehensive document that outlines the requirements for a web-based workload management system. This document will serve as a crucial reference point for various stakeholders involved in the project, including clients, developers, project managers, UI/UX designers, testers, IT administrators, and pharmacy staff and managers. The document will cover the system's objectives, functionalities, user roles, technical specifications, testing procedures, and project timeline.

3. What are the goals of the task? Please describe in detail.

- Clarity and Understanding: The primary goal is to ensure that all stakeholders have a clear and comprehensive understanding of the workload management system's requirements and expectations. This includes both technical and non-technical aspects of the project.

- Alignment: Achieve alignment among the project team and stakeholders regarding the project's scope, objectives, and functionalities. This alignment is crucial for successful project execution.

- Guidance: Provide guidance to developers, designers, testers, and IT administrators on their specific responsibilities and areas of focus within the project.

- Quality Assurance: Lay out the groundwork for testing and quality assurance, ensuring that all relevant functionalities are tested thoroughly to meet quality standards.

- Project Planning: Assist project managers in planning, executing, and monitoring the project by providing a clear roadmap and milestones.

4. Success or completion criteria. Please describe in detail.
The task will be considered successful and complete when the following criteria are met:

- Document Completeness: The document must cover all essential aspects of the web-based workload management system, leaving no ambiguities or gaps in requirements.

- Stakeholder Understanding: All relevant stakeholders, including clients, developers, project managers, UI/UX designers, testers, IT administrators, and pharmacy staff and managers, should have a comprehensive understanding of their roles and responsibilities within the project.

- Alignment: There should be a consensus among stakeholders regarding the project's scope, objectives, and functionalities.

- Clarity: The document should be clear and concise, using language that is understandable to both technical and non-technical stakeholders.

- Timeline and Milestones: The project timeline and milestones should be clearly defined, allowing project managers to plan and execute the project effectively.

- Quality Assurance Framework: The document should provide a framework for testing and quality assurance, ensuring that all functionalities are adequately tested.

5. Allocated time
22 days

6. Start date and end date of the issue/task
Start Date: 28th August 2023
End Date: 23rd September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Khairyl (khairusyaidy)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
In-Progress

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by BenjaminChiam** [comment]
Describe the work done in detail.
This document outlines the requirements for a web-based workload management system. It covers the system's objectives, functionalities, and the roles of different users. The document is organized into the following sections:

- Introduction
- System Requirements
- User Roles and Permissions
- Data Management
- Technical Requirements
- Testing and Quality Assurance
- Timeline and Milestones


Has this work been committed to the repo?
Yes.

How does the work affect 4. Success or completion criteria?

- Meticulous listing of plans and stages of software development has been placed in our team's documents to set targets and track progress.

- The objectives, functionalities, and the roles of different users has been recorded down in the document for clarity with the development team as well as the client to ensure both parties are on the same page.

Start date and end date of the work done
Start Date: 18th September 2023
End Date: 23rd September 2023

**Comment by BenjaminChiam** [comment]
Section completed, marked as closed
