### ISSUE TITLE
1.2.1 Product Overview

### ISSUE THREAD

**Issue by khairusyaidy** [khairusyaidy/P7-1#9]
1. Task title ID: #9
2. What is the task about? Please describe in detail.
The task involves creating a comprehensive System's Architecture diagram that visually represents the components, modules, and their interactions within the WMS. This diagram should showcase the system's architecture, including both the front-end and back-end components, as well as how it interfaces with external entities and databases. It should provide a clear understanding of the WMS's structure and how it functions within the pharmacy chain's operational environment.

3. What are the goals of the task? Please describe in detail.

- Clarity: The primary goal is to create a visually clear and informative System's Architecture diagram that can be used for reference by development teams, stakeholders, and anyone involved in the project.

- Comprehensive Representation: Ensure that all relevant components and their interactions are accurately depicted in the diagram. This includes the web-based interface, database connections, user roles, and any external dependencies.

- Alignment with Requirements: The diagram should align with the product's requirements and specifications, highlighting how the WMS addresses the specific needs of the pharmacy chain.

4. Success or completion criteria. Please describe in detail.
The task can be considered successful and completed when the following criteria are met:

- A System's Architecture diagram for the WMS is created, featuring all necessary components and their connections.

- The diagram is reviewed and approved by relevant stakeholders, ensuring that it accurately represents the system's architecture.

- The diagram is in a format that can be easily shared and referenced by the development team, project managers, and other stakeholders.

- The task owner ensures that any necessary updates or revisions are made based on feedback and evolving project requirements.

5. Allocated time
5 days

6. Start date and end date of the issue/task
Start Date: 18th September 2023
End Date: 23rd September 2023

7. Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Khairyl (khairusyaidy)

8. The status of the task. This is usually "To-Do" initially To-Do / In-Progress / Completed
In-Progress

9. What is the Priority of the task? HIGH / MEDIUM / LOW
HIGH

**Comment by mdmarhakim** [comment]
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect 4. Success or completion criteria?
4. Start date and end date of the work done

**Comment by mdmarhakim** [comment]
Describe the work done in detail.
Explanation on the product overview and providing a System’s Architecture diagram to illustrate how this product interacts with the environment and in what context it is being used.  

Has this work been committed to the repo?
Yes.

How does the work affect 4. Success or completion criteria?

- A System's Architecture diagram for the WMS is created, featuring all necessary components and their connections.

- The diagram is reviewed and approved by relevant stakeholders, ensuring that it accurately represents the system's architecture.

Start date and end date of the work done
Start Date: 18th September 2023
End Date: 23rd September 2023
